### ISSUE TITLE
StringSearcher: Masking issue

### ISSUE THREAD

**Issue by CrazyWonton** [mtimmerm/dfalex#3]
After creating a search and replace builder with the following code:

`SearchAndReplaceBuilder builder = new SearchAndReplaceBuilder();
builder.addReplacement(Pattern.regexI("(<name>)"), StringReplacements.DELETE);
Function<String, String> replacer = builder.buildStringReplacer();`

then running the XML document string (found [here](https://github.com/FasterXML/aalto-xml/blob/master/pom.xml)) through it, the StringSearcher class fails on line 110 during the assert statement.

**Comment by mtimmerm** [comment]
Thanks.  I'll look into that this week.  Did you run it on the whole document through as a single string?

**Comment by CrazyWonton** [comment]
Yep, I sent the XML in as a single string. I noticed that reducing the size
of the string had little to no effect, however modifying the number of
occurrences of "<name>" in the string resolved the issue.

Hope this helps.

Thanks,
Kevin

**Comment by mtimmerm** [comment]
Fixed. 1.0.1 should show up on maven central soon
